sudo: required
language: generic
services:
  - docker
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; 
    then docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    make push;
    fi
env:
  global:
    - secure: TfCpK/O6W3fLunhyGhe4L9f8FpWC7/4xN484jZEcWVKaA1J260/+6RoKqihiYqFF0cQ3lM0diMZobZpyW8D85BnWiEPiaXgDtbeFIFLisderR+HxG2vGwEJshmzBPW+C5pLYqm6TFeEYx6JH0M+RfbdLtSERuoYHMSPqECYPr0VCCxaeZMGRfiG7aixTe9SJ9uiU76A5NNOMqi9Q4PyMCKOM6cC6r7YdO+CY6/cK5H56KWW+U3Nk1rAG//S7m9l/USBg2DUkdfMJBP1RwBj6PQd4bTyKIKSs3LHCEpnIF8Gc1WzGCcauWkFV9NM5GDlo0GOrOKyA6wVNZ5AwjYLybY7Bp5WvygAfl/nw+N+8eMLOEbMwRAX8xdSbIwC2q/xb495HkY8hgEzENriE5L/gQW2vTcQOkkvQDIl89nRoYg/t/6y1yuNHQ6sRjw5u+O091dmHr4aoKWn2pmjvLOZ1PYio7xc4zZOmQ13w6A9M1uzevNNAq9RQMLkIQj6580K9mHry61Uk++07kpCFw7tBBuEMb+N+Wgu93+7i1bJJ0Rbna98jxjFasbTfwBSgmI2Z3MC3dW50xy54qV1tRucm7/+Tl3XwvoGT+VePNDSz++BvOBvI8cl2kgohAvcVoRSkwqeoCOJ38Aa2KdMGbBnyRtY+5raFP2VJCsWEWuwwRiA=
    - secure: hqSR6OZwldO5+P16pvoCTlR1l9CBRbe3ERYkQWuHmVBTPf3ZFjT51ZLz0OMhiaQgT9IHXan8ZVSM2U4KVsEBrbJzBPPvXZWsqQBeXlgrLonp4ucSSmp6SET5PvI1Qz22AEQF26brgl7+W6zFqygv1TXcE3lhBKvaYRZpIVyGgkst3IdZ2kp7UnPtc+8a4Olsy+N1lRvsL0c38i7tx3gZMJkMECTmyt7NGbmevVDPuN+e/6Nx0PxBkdPAjC85wErGkIpIyBiBPlox+tDfDhf9Y/hrWlSfu6ERqKzwf4fyKVyOxoBn4QD27Pse8N2pltz28MlIKhMC+ikzI2gNwrBvUxL7PtOgX1+eWLC0N+eHR+7xUzQ9imFDr4B5LpwMzoODiRqeQsM+iVToKeghF4sWBwLYebftjaloltllc7oGKHzhQfUIV2PQlGRb/Z08iviNN0Z81QizEN3chSGNkfUwV6UHV7+0R8InOhp3XHaWiBqMBhggzk7cb8kn2p6H0RR4iJyELznaNnIcxnxS5YjYS3kWLwO/Dsvz5bxPyiJleVs39G8lYLf4q6lGKmWAgX+MywPOmS7kViEsncg80GXWWiajOSY4DNDDJFGyYG1i6xE6mLj78zNqEpORjEke8QvW1YHQSvJokJLK8AoWI9tYTcg6vRENCKzNmgbSv3GgjWE=
